quarkus.index-dependency.rimfrost-service-sid-api-jaxrs-spec.group-id=se.fk.rimfrost.sid
quarkus.index-dependency.rimfrost-service-sid-api-jaxrs-spec.artifact-id=rimfrost-service-sid-api-jaxrs-spec

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true

# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-sid
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false
